version: 2
updates:
  - package-ecosystem: composer
    directory: /
    target-branch: develop
    schedule:
      interval: weekly
    cooldown:
      default-days: 7
    labels: [chore, dependencies]
    commit-message:
      prefix: "chore"
    groups:
      composer:
        patterns:
          - "*"

  - package-ecosystem: npm
    directory: /
    target-branch: develop
    schedule:
      interval: weekly
    cooldown:
      default-days: 7
    labels: [chore, dependencies]
    commit-message:
      prefix: "chore"
    groups:
      npm:
        patterns:
          - "*"

  - package-ecosystem: github-actions
    directory: /
    target-branch: develop
    schedule:
      interval: weekly
    cooldown:
      default-days: 7
    labels: [chore, dependencies]
    commit-message:
      prefix: "chore"
    groups:
      github-actions:
        patterns:
          - "*"
