blank_issues_enabled: false
contact_links:
  - name: Discussions
    url: https://github.com/builtnoble/duration-fieldtype/discussions
    about: For general questions that aren't a bug report or feature request.
