name: Lint code style issues

on:
  pull_request:

permissions: {}

jobs:
  lint:
    permissions:
      contents: read
    uses: builtnoble/.github/.github/workflows/php-code-style-lint.yml@057258c6bbb173fc64da8f7b15d93fd837ced874 # v1
    with:
      php-extensions: mbstring
