name: Tests

on:
  push:
    branches: [main, develop]
  pull_request:
    branches: [main, develop]

permissions: {}

concurrency:
  group: ${{ github.workflow }}-${{ github.ref }}
  cancel-in-progress: true

jobs:
  tests:
    permissions:
      contents: read
    uses: builtnoble/.github/.github/workflows/php-package-tests.yml@v1
    with:
      php-extensions: mbstring
