name: GitHub Actions Security Analysis

on:
  push:
    branches: [main, develop]
    paths:
      - '.github/**.yml'
  pull_request:
    paths:
      - '.github/**.yml'

permissions: {}

concurrency:
  group: ${{ github.workflow }}-${{ github.ref }}
  cancel-in-progress: true

jobs:
  zizmor:
    permissions:
      contents: read
    uses: builtnoble/.github/.github/workflows/github-actions-security-scan.yml@057258c6bbb173fc64da8f7b15d93fd837ced874 # v1
